### ISSUE TITLE
Support free trials

### ISSUE THREAD

**Issue by bojanz** [bojanz/commerce_recurring#3]
This is not required for our initial version, but is important to think about. Most solutions have some kind of support for free trials. It starts with a trial_interval in the billing schedule. For example, a monthly schedule where the 1st month is a trial. That ensures that we don't charge the customer for the first cycle.

It's questionable / worth discussing whether free trials should be invoiced at all. If they shouldn't, then there should not be a recurring order for them.

**Comment by bojanz** [comment]
I've done some research.

1) The trial period is the period before the billing cycles start. No invoice.
2) Intervals often don't match.

So, a monthly prepaid service might have a "14 day" trial. Then, close to the expiry of the 14 days, the customer is notified and given a chance to cancel their subscription. If they don't, we automatically start billing (create the first billing cycle and recurring order, in case of prepayment charge the card).

**Comment by wizonesolutions** [comment]
How will trials and licenses interact? Will trials activate the licenses and then deactivate them if the trial expires without renewal, more or less the same way as regular billing periods?

Assuming so, will some sort of option indicating that the license was activated/deactivated because of a trial be passed to the relevant method (in case the license type is aware of Commerce Recurring and wants to do something special)?

**Comment by bojanz** [comment]
Generally free trials continue into paid periods, unless the subscription is cancelled.
Since the underlying license is created with an unlimited expiration, and then maintained together with the subscription, it works out of the box.

A license might want to know if it's currently in trial, but I think that the only thing we can do is ensure Recurring throws the appropriate events, which can then be used by custom code that sets the appropriate flag on licenses.

**Comment by bojanz** [comment]
Moving to d.o: https://www.drupal.org/node/2919596
